/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package appcds;

import java.util.Optional;
import java.util.stream.Stream;

enum DayOfWeek {
    MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY;

    public static Optional<DayOfWeek> fromString(String day) {
        return Stream.of(DayOfWeek.values()).filter(dow -> dow.name().equalsIgnoreCase(day)).findFirst();
    }
}

public class App {
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Stream.of(args)
              .map(DayOfWeek::fromString)
              .forEach(od -> od.ifPresent(d -> System.out.println(String.format("On %s I have %d lessons",
                      d,
                      howManyLessons(d)))));
    }

    private static int howManyLessons(DayOfWeek day) {
        return switch (day) {
            case MONDAY, FRIDAY -> 6;
            case TUESDAY -> 7;
            case THURSDAY, WEDNESDAY -> 8;
            case SATURDAY, SUNDAY -> 0;
        };
    }

    private String getGreeting() {
        return "Hello world.";
    }
}
